COMPLETE: Tab Navigation for Home, Register Device and Profile page
Error: Error: A navigator can only contain 'Screen', 'Group' or 'React.Fragment' as its direct children (found 'TabNavigation'). To render this component in the navigator, pass it in the 'component' prop to 'Screen'.
It's because {user ? (
          <TabNavigation />
        ) : (
Should modify it to {user ? (
          <Stack.Screen name="Tab" component={TabNavigation} />
        )